name = "exactQmodule"
uuid = "f1e74a92-8dd5-11e9-17ed-634788f054c4"
authors = ["RaGaTensor <Raffael.Gawatz@gmx.de>"]
version = "0.1.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
